web/urls.py
from django.conf.urls import url, include
from django.contrib import admin


admin.autodiscover()
from web.views import welcome,session_test,register,IndexView,index
from restaurants.views import  menu, list_restaurants,comment,list,list_users
import restaurants
from post.views import recv_data,show,load_data,last,findmachine,pr
from django.contrib.auth.views import login,logout
from django.contrib.auth.decorators import login_required
from web import views
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from data.views import overview #loaddata,revisedata, deletedata
#from user_output.views import overview2
from personal.views import plotdata
from django.urls import path




#urlpatterns = [
#    path('admin/', admin.site.urls),
#]
urlpatterns =[
    url(r'^$',index),
    url(r'^admin/',admin.site.urls),
    #url(r'^menu/(\d{1,5})/$',menu),
    url(r'^menu/(?P<pk>\d+)/$',restaurants.views.MenuView.as_view()),
    #url(r'^menu/(?P<pk>\d+)/$',DetailView.as_view(template_name='menu.html')),  #not template view
    url(r'^welcome/$',welcome),
    #url(r'^restaurants_list/$',list_restaurants),
    url(r'^restaurants_list/$',login_required(restaurants.views.RestaurantsView.as_view())),
    #url(r'^restaurants_list/$',login_required(TemplateView.as_view(template_name='restaurants_list.html'))),
    url(r'^users_list/$',list_users),
    #url(r'^comment/(?P<id>\d{1,5})/$',comment),
    url(r'^comment/(?P<pk>\d+)/$',restaurants.views.CommentView.as_view()),
    url(r'^math/$',session_test),
    url(r'^accounts/login/$',login),
    url(r'^accounts/logout/$',logout),
    #url(r'^index/$',views.IndexView.as_view()),
    url(r'^index/$',TemplateView.as_view(template_name='index1.html')),
    url(r'^accounts/register/$',register),
    url(r'^overview/$',overview),
    #url(r'^loaddata/$',loaddata),
    #url(r'^revisedata/$',revisedata),
    #url(r'^deletedata/$',deletedata),
    #url(r'^overview2/$',overview2),
    url(r'^plot/$',plotdata),
    url(r'^here/$',views.HereView.as_view()),
    url(r'^post/$',recv_data),
    url(r'^show/$',show),
    url(r'^load/$',load_data),
    url(r'^last/$',last),
    url(r'^findmachine/$',findmachine),
    url(r'^pr/$',pr),
]

restaurants/models.py
from django.db import models

# Create your models here.
from django.db import models

# Create your models here.
class Restaurant(models.Model):
   name=models.CharField(max_length=20)
   phone_number=models.CharField(max_length=20)
   address=models.CharField(max_length=50, blank=True)

   def __str__(self):
        return self.name

class Food(models.Model):
   name=models.CharField(max_length=20)
   price=models.DecimalField(max_digits=3,decimal_places=0)
   comment=models.CharField(max_length=50, blank=True)
   is_spicy=models.BooleanField(default=False)
   restaurant=models.ForeignKey(Restaurant,on_delete=models.CASCADE)
   
   def __str__(self):
        return self.name

class Comment(models.Model):
   content=models.CharField(max_length=255)
   visitor=models.CharField(max_length=255)
   email=models.EmailField(max_length=255)
   date_time=models.DateTimeField()
   restaurant=models.ForeignKey(Restaurant,on_delete=models.CASCADE)
   class Meta:
       ordering=['date_time']
       permissions=(("can_comment","Can comment"),)

templates/base.html
<!doctype html> 
<html>
    <head>
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <nav>
            | <a href="/restaurants_list/"> Restaurants List </a> |
            {% if request.user.is_authenticated %}
                {{ request.user }}
                |<a href="/accounts/logout/"> Log Out </a>|
            {% else %}
                |<a href="/accounts/login/"> Log In </a>|
                <a href="/accounts/register/"> Register </a>
            {% endif %}
            <a href='overview/?id=all'> Overview data </a>|
        </nav>
        <h2>{% block h2 %}{% endblock %}</h2>
        {% block content %}{% endblock %}
    </body>
</html>

templates/body.html
<h2> Welcome to Restaurant King </h2>
        {% if request.user.is_authenticated %}
             <p> {{request.user}} sign in already 
                 <a href="/accounts/logout/"> log out</a>            
             </p>
             <a href="/restaurants_list/"> Restaurants List</a>
        {% else %}
             <p> not sign in yet <a href="/accounts/login/"> sign in</a> </p>

        {% endif %}
            <p> if you don't have account, plz <a href="/accounts/register/">regi</a></p>

templates/comments.html
<!doctype html>
<html>
    <head>
        <title> Comments </title>
        <meta charset='utf-8'>
    </head>
    <body>
        <h2>{{ r.name }}的評價</h2>
        {% if r.comment_set.all %}
            <p>目前共有{{ r.comment_set.all|length }}條評價</p>
            <table>
                <tr>
                    <th>留言者</th>
                    <th>時間</th>
                    <th>評價</th>
                </tr>
            {% for c in r.comment_set.all %}
                <tr>
                    <td> {{ c.visitor }} </td>
                    <td> {{ c.date_time | date:"F j, Y" }} </td>
                    <td> {{ c.content }} </td>
                </tr>
            {% endfor %}
            </table>
        {% else %}
            <p>無評價</p>
        {% endif %}

        <br /><br />
        <form action="" method="post">
        <div class="form-group">
        <label for="visitor">留言者:</label>
            {{ form.visitor }}
            {{ form.visitor.errors}}
        </div>
        <div class="form-group">
        <label for="email">Email:</label>
            {{ form.email }}
            {{ form.email.errors }}
        </div>
        <div class="form-group">
        <label for="content">評價:</label>
            <br /> 
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
               {{ form.content }}
               {{ form.content.errors }}
        </div>
        <input type="submit" value="給予評價">
        </form>
    </body>
</html>

templates/comments1.html
<!doctype html>
<html>
    <head>
        <title> Comments </title>
        <meta charset='utf-8'>
    </head>
    <body>
        <h2>{{ r.name }}的評價</h2>
        {% if r.comment_set.all %}
            <p>目前共有{{ r.comment_set.all|length }}條評價</p>
            <table>
                <tr>
                    <th>留言者</th>
                    <th>時間</th>
                    <th>評價</th>
                </tr>
            {% for c in r.comment_set.all %}
                <tr>
                    <td> {{ c.visitor }} </td>
                    <td> {{ c.date_time | date:"F j, Y" }} </td>
                    <td> {{ c.content }} </td>
                </tr>
            {% endfor %}
            </table>
        {% else %}
            <p>無評價</p>
        {% endif %}

        <br /><br />
        {% if f.errors %}
        <p style="color:red;">
            follow the hint to revise the answers
        </p>
        {% endif %}
        <form action="" method="post">
            <table>
             {{ f.as_table}}
            </table>

            <input type="submit" value="給予評價">
        </form>
    </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %} Home Page {% endblock %}
{% block h2 %} My website {% endblock %}

{% block content %}
    <p> Welcome to mysite</p>
{% endblock %}

templates/index1.html
{% extends 'base.html' %}

{% block title %} Home Page {% endblock %}
{% block h2 %} Restaurants Mother Fucker {% endblock %}

{% block content %}
    <p> Welcome to Restaurants Mother Fucker</p>
    <p> this is class mode </p>
{% endblock %}

templates/iot.html
<!doctype html>
<html>
    <head>
        <title> Cloud Monitor </title> <a href="/show/"> Refresh </a>
        <meta charest='utf-8'>
    </head>
    <body>
        <h2> Current </h2>
                <tr>
                    <br> Current Tempreture : {{a}} C -- {{b}} </br>
                    <br> Current Humidity   : {{c}} % -- {{d}} </br>
                    <br> Current Status     : {{e}}   -- {{f}} </br>
                    <br>  </br>
                    <br> Avreage Temperture : {{g}} </br>
                    <br> Average Humidity   : {{h}} </br>

                </tr>
        <br></br>  
        <form action="" method="post">
         <table>
          <label for="Lux"> Lux(0~100)  :   </label>{% csrf_token %}
          <input type="text" name="Lux" size=3 id="Lux">
          <input type="submit" value="Adjust">
         </table>
        </form>

    </body>
</html>

templates/login1.html
<!doctype html>
<html>
    <head>
        <title> Signin System </title>
        <meta charest='utf-8'>
    </head>
    <body>
        <from action="" method="post">
          <label for="username"> Username: </label>{% csrf_token %}
          <input type="text" name="username" value="{{username}}" id="username"> <br/>
          <label for="password"> Password: </label>
          <input type="password" name="password" value="" id="password"> <br/>
          <input type="submit" value="sign in"/>
        </form>
    </body>
</html>

templates/math.html
<html>
    {{s_info}}
</html>

templates/menu.html
<!doctype html>
<html>
    <head>
        <title> Menu </title>
        <meta charest='utf-8'>
        <style>
           table, th td{
              border: 1px solid black;
           }
        </style>
      </head>
      <body>
          <p>You are now here {{path}} </p>
		  <h2>{{restaurant.name}}'s menu</h2>
		  {% if restaurant.food_set.all %}
		  <p> this restaurant has {{restaurant.food_set.all|length}} dishes</p>
		  <table>
		     <tr>
		         <th>food_name</th>
		         <th>price</th>
		         <th>is_spicy</th>
		         <th>comment</th>
		     </tr>
		     {% for food in restaurant.food_set.all %}
		     <tr>
		         <td>{{food.name}}</td>
		         <td>{{food.price}}</td>
		         <td>{% if food.is_spicy %} spicy {% else %}
		                                    not spicy{% endif %}</td>
		         <td>{{food.comment}}</td> 
		     </tr>
		     {% endfor %}
		</table>
		{% else %}
		<p>nothing</p>
		{% endif %}
      </body>
</html>

templates/register.html
<html>
   <body>
      <h1> New Redister</h1>

        <form action="" method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="register">
        </form>
   </body>
</html>

templates/restaurants_list.html
<!doctype html>
<html>
    <head>
        <title> Restaurants </title> <a href="/"> Home Page </a>
        <meta charest='utf-8'>
    </head>
    <body>
        <h2> Restaurants list </h2>
        <form action="/menu/" method="get">
        <table>
            <tr>
                <th>select</th>
                <th>name</th>
                <th>phone_number</th>
                <th>address</th>
  
                   <th>comment</th>

            </tr>
            {% for r in restaurants %}
                <tr>
                    <td> <a href="/menu/{{r.id}}/"> menu </a> </td>
                    <td> {{ r.name }} </td>
                    <td> {{ r.phone_number }} </td>
                    <td> {{ r.address }} </td>

                       <td> <a href="/comment/{{r.id}}/"> comment </a> </td>
     
                </tr>
            {% endfor %}
        </table>
        </form>
    </body>
</html>

templates/user_list.html
{% extends 'base.html' %}

{% block title %} Users List {% endblock %}
{% block h2 %} Users List {% endblock %}

{% block content %}
    <table>
        <tr>
           <th> Account </th>
           <th> Name    </th>
        </tr>
        {% for u in users %}
            <tr>
               <td> {{ u.username }} </td>
               <td> {{ u.last_name }} {{ u.first_name }} </td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/welcome.html
<html>
    <head>
        <title> Welcome mother fucker </title>
    </head>
    <body>
        <form action="/welcome/" method="get">
            <label for="user_name"> Your name</label>
            <input id="user_name" type="text" name="user_name">
            <input type="submit" value="enter the site">
        </form>
    </body>
</html>